version: 0.2

phases:
  install:
    runtime-versions:  # ADD THIS - Fixes "No runtime version" warning
      docker: 20       # Pre-installed Docker
    commands:
      - yum update -y
      - yum install -y docker curl
      - service docker start
      - usermod -a -G docker $(whoami)
      
  pre_build:  # BUILD
    commands:
      - echo "Building Apache container..."
      - docker build -t httpd-demo:latest .
      
  build:       # TEST
    commands:
      - docker run -d -p 8080:80 --name test-app httpd-demo:latest
      - sleep 15
      - curl -f http://localhost:8080 || exit 1
      - curl http://localhost:8080 | grep "Satyajit" || exit 1
      - echo "✅ All tests PASSED!"
      
  post_build:
    commands:
      - docker stop test-app || true
      - docker rm test-app || true

artifacts:
  files:
    - install-httpd.sh
    - appspec.yml
    - index.html

