version: 0.2

phases:
  install:
    commands:
      - docker info
      
  pre_build:
    commands:
      - echo "Building Apache container..."
      - docker build -t httpd-demo .

  build:
    commands:
      - echo "Starting container..."
      - docker run -d -p 8080:80 --name test-app httpd-demo
      - sleep 35
      - docker logs test-app  # Debug logs
      # TEST 1: Docker exec INSIDE container
      - docker exec test-app wget -qO- localhost:80 || exit 1
      # TEST 2: Verify content  
      - docker exec test-app grep "Satyajit" /usr/local/apache2/htdocs/index.html || exit 1
      - echo "✅ All tests PASSED!"

  post_build:
    commands:
      - docker stop test-app
      - docker rm test-app

artifacts:
  files:
    - install-httpd.sh
    - appspec.yml
    - index.html

