version: 0.2
phases:
  install:
    commands:
      - docker info
  pre_build:
    commands:
      - docker build -t httpd-demo .
  build:
    commands:
      - docker run -d --name test httpd-demo
      - sleep 40
      - docker exec test sh -c "wget -qO- localhost:80 || curl -f localhost:80" || exit 1
      - docker exec test cat /usr/local/apache2/htdocs/index.html
      - echo "✅ TESTS PASSED"
  post_build:
    commands:
      - docker stop test && docker rm test
artifacts:
  files:
    - install-httpd.sh
    - appspec.yml
    - index.html

