version: 0.2

phases:
  install:
    commands:
      # Docker is ALREADY RUNNING in Privileged mode
      - docker info
      - echo "Docker ready!"
      
  pre_build:  # BUILD
    commands:
      - echo "Building Apache container..."
      - docker build -t httpd-demo .
      - echo "✅ Build complete!"
      
  build:  # TEST
    commands:
      - echo "Running tests..."
      - docker run -d -p 8080:80 --name test-app httpd-demo
      - sleep 10
      - curl -f http://localhost:8080 || exit 1
      - curl http://localhost:8080 | grep "Satyajit" || exit 1
      - echo "✅ Tests PASSED!"
      
  post_build:
    commands:
      - docker stop test-app || true
      - docker rm test-app || true

artifacts:
  files:
    - install-httpd.sh
    - appspec.yml
    - index.html

