version: 0.2

phases:
  install:
    commands:
      - docker info
      
  pre_build:
    commands:
      - echo "Building Apache container..."
      - docker build -t httpd-demo .
      
  build:
    commands:
      - echo "Starting container for testing..."
      - docker run -d -p 8080:80 --name test-app httpd-demo
      - echo "Waiting for Apache to start (30s)..."
      - sleep 30                    # ← INCREASED FROM 10s
      - docker logs test-app         # Debug: see startup logs
      - curl -f http://localhost:8080 || exit 1
      - curl http://localhost:8080 | grep "Satyajit" || exit 1
      - echo "✅ All tests PASSED!"
      
  post_build:
    commands:
      - docker stop test-app
      - docker rm test-app

artifacts:
  files:
    - install-httpd.sh
    - appspec.yml
    - index.html

